package com.primos.core.persistence.PA;
// Generated 14/10/2018 08:08:00 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Correo generated by hbm2java
 */
@Entity
@Table(name="correo"
)
public class Correo  implements java.io.Serializable {


     private long idcorreo;
     private boolean bitactivo;
     private boolean bitprimario;
     private long idpersona;
     private String strcorreo;

    public Correo() {
    }

    public Correo(long idcorreo, boolean bitactivo, boolean bitprimario, long idpersona, String strcorreo) {
       this.idcorreo = idcorreo;
       this.bitactivo = bitactivo;
       this.bitprimario = bitprimario;
       this.idpersona = idpersona;
       this.strcorreo = strcorreo;
    }
   
     @Id 

    
    @Column(name="idcorreo", nullable=false)
    public long getIdcorreo() {
        return this.idcorreo;
    }
    
    public void setIdcorreo(long idcorreo) {
        this.idcorreo = idcorreo;
    }

    
    @Column(name="bitactivo", nullable=false)
    public boolean isBitactivo() {
        return this.bitactivo;
    }
    
    public void setBitactivo(boolean bitactivo) {
        this.bitactivo = bitactivo;
    }

    
    @Column(name="bitprimario", nullable=false)
    public boolean isBitprimario() {
        return this.bitprimario;
    }
    
    public void setBitprimario(boolean bitprimario) {
        this.bitprimario = bitprimario;
    }

    
    @Column(name="idpersona", nullable=false)
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }

    
    @Column(name="strcorreo", nullable=false, length=30)
    public String getStrcorreo() {
        return this.strcorreo;
    }
    
    public void setStrcorreo(String strcorreo) {
        this.strcorreo = strcorreo;
    }




}


