package com.primos.core.persistence.PA;
// Generated 14/10/2018 08:08:00 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
)
public class Direccion  implements java.io.Serializable {


     private long iddireccion;
     private boolean bitactivo;
     private boolean bitprimario;
     private long iddominio;
     private long idpersona;
     private String strdireccion;

    public Direccion() {
    }

    public Direccion(long iddireccion, boolean bitactivo, boolean bitprimario, long iddominio, long idpersona, String strdireccion) {
       this.iddireccion = iddireccion;
       this.bitactivo = bitactivo;
       this.bitprimario = bitprimario;
       this.iddominio = iddominio;
       this.idpersona = idpersona;
       this.strdireccion = strdireccion;
    }
   
     @Id 

    
    @Column(name="iddireccion", nullable=false)
    public long getIddireccion() {
        return this.iddireccion;
    }
    
    public void setIddireccion(long iddireccion) {
        this.iddireccion = iddireccion;
    }

    
    @Column(name="bitactivo", nullable=false)
    public boolean isBitactivo() {
        return this.bitactivo;
    }
    
    public void setBitactivo(boolean bitactivo) {
        this.bitactivo = bitactivo;
    }

    
    @Column(name="bitprimario", nullable=false)
    public boolean isBitprimario() {
        return this.bitprimario;
    }
    
    public void setBitprimario(boolean bitprimario) {
        this.bitprimario = bitprimario;
    }

    
    @Column(name="iddominio", nullable=false)
    public long getIddominio() {
        return this.iddominio;
    }
    
    public void setIddominio(long iddominio) {
        this.iddominio = iddominio;
    }

    
    @Column(name="idpersona", nullable=false)
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }

    
    @Column(name="strdireccion", nullable=false, length=30)
    public String getStrdireccion() {
        return this.strdireccion;
    }
    
    public void setStrdireccion(String strdireccion) {
        this.strdireccion = strdireccion;
    }




}


