package com.primos.core.persistence.PA;
// Generated 14/10/2018 08:08:00 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dominio generated by hbm2java
 */
@Entity
@Table(name="dominio"
)
public class Dominio  implements java.io.Serializable {


     private long iddominio;
     private Long iddominiopadre;
     private long idtipodominio;
     private String strdescripcion;

    public Dominio() {
    }

	
    public Dominio(long iddominio, long idtipodominio, String strdescripcion) {
        this.iddominio = iddominio;
        this.idtipodominio = idtipodominio;
        this.strdescripcion = strdescripcion;
    }
    public Dominio(long iddominio, Long iddominiopadre, long idtipodominio, String strdescripcion) {
       this.iddominio = iddominio;
       this.iddominiopadre = iddominiopadre;
       this.idtipodominio = idtipodominio;
       this.strdescripcion = strdescripcion;
    }
   
     @Id 

    
    @Column(name="iddominio", nullable=false)
    public long getIddominio() {
        return this.iddominio;
    }
    
    public void setIddominio(long iddominio) {
        this.iddominio = iddominio;
    }

    
    @Column(name="iddominiopadre")
    public Long getIddominiopadre() {
        return this.iddominiopadre;
    }
    
    public void setIddominiopadre(Long iddominiopadre) {
        this.iddominiopadre = iddominiopadre;
    }

    
    @Column(name="idtipodominio", nullable=false)
    public long getIdtipodominio() {
        return this.idtipodominio;
    }
    
    public void setIdtipodominio(long idtipodominio) {
        this.idtipodominio = idtipodominio;
    }

    
    @Column(name="strdescripcion", nullable=false, length=50)
    public String getStrdescripcion() {
        return this.strdescripcion;
    }
    
    public void setStrdescripcion(String strdescripcion) {
        this.strdescripcion = strdescripcion;
    }




}


