package com.primos.core.persistence.PA;
// Generated 14/10/2018 08:08:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
)
public class Persona  implements java.io.Serializable {


     private long idpersona;
     private boolean bitactivo;
     private Date dtmfechacreacion;
     private String strapellido;
     private String strnombre;
     private String strnumerodocumento;

    public Persona() {
    }

    public Persona(long idpersona, boolean bitactivo, Date dtmfechacreacion, String strapellido, String strnombre, String strnumerodocumento) {
       this.idpersona = idpersona;
       this.bitactivo = bitactivo;
       this.dtmfechacreacion = dtmfechacreacion;
       this.strapellido = strapellido;
       this.strnombre = strnombre;
       this.strnumerodocumento = strnumerodocumento;
    }
   
     @Id 

    
    @Column(name="idpersona", nullable=false)
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }

    
    @Column(name="bitactivo", nullable=false)
    public boolean isBitactivo() {
        return this.bitactivo;
    }
    
    public void setBitactivo(boolean bitactivo) {
        this.bitactivo = bitactivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dtmfechacreacion", nullable=false, length=13)
    public Date getDtmfechacreacion() {
        return this.dtmfechacreacion;
    }
    
    public void setDtmfechacreacion(Date dtmfechacreacion) {
        this.dtmfechacreacion = dtmfechacreacion;
    }

    
    @Column(name="strapellido", nullable=false, length=80)
    public String getStrapellido() {
        return this.strapellido;
    }
    
    public void setStrapellido(String strapellido) {
        this.strapellido = strapellido;
    }

    
    @Column(name="strnombre", nullable=false, length=80)
    public String getStrnombre() {
        return this.strnombre;
    }
    
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    
    @Column(name="strnumerodocumento", nullable=false, length=50)
    public String getStrnumerodocumento() {
        return this.strnumerodocumento;
    }
    
    public void setStrnumerodocumento(String strnumerodocumento) {
        this.strnumerodocumento = strnumerodocumento;
    }




}


