package com.primos.core.persistence.PA;
// Generated 14/10/2018 08:08:00 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonaDominioId generated by hbm2java
 */
@Embeddable
public class PersonaDominioId  implements java.io.Serializable {


     private long iddominio;
     private long idpersona;

    public PersonaDominioId() {
    }

    public PersonaDominioId(long iddominio, long idpersona) {
       this.iddominio = iddominio;
       this.idpersona = idpersona;
    }
   


    @Column(name="iddominio", nullable=false)
    public long getIddominio() {
        return this.iddominio;
    }
    
    public void setIddominio(long iddominio) {
        this.iddominio = iddominio;
    }


    @Column(name="idpersona", nullable=false)
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonaDominioId) ) return false;
		 PersonaDominioId castOther = ( PersonaDominioId ) other; 
         
		 return (this.getIddominio()==castOther.getIddominio())
 && (this.getIdpersona()==castOther.getIdpersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIddominio();
         result = 37 * result + (int) this.getIdpersona();
         return result;
   }   


}


