package com.primos.core.persistence.PA;
// Generated 14/10/2018 08:08:00 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
)
public class Telefono  implements java.io.Serializable {


     private long idtelefono;
     private boolean bitactivo;
     private boolean bitprimario;
     private long iddominio;
     private long idpersona;
     private String strtelefono;

    public Telefono() {
    }

    public Telefono(long idtelefono, boolean bitactivo, boolean bitprimario, long iddominio, long idpersona, String strtelefono) {
       this.idtelefono = idtelefono;
       this.bitactivo = bitactivo;
       this.bitprimario = bitprimario;
       this.iddominio = iddominio;
       this.idpersona = idpersona;
       this.strtelefono = strtelefono;
    }
   
     @Id 

    
    @Column(name="idtelefono", nullable=false)
    public long getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(long idtelefono) {
        this.idtelefono = idtelefono;
    }

    
    @Column(name="bitactivo", nullable=false)
    public boolean isBitactivo() {
        return this.bitactivo;
    }
    
    public void setBitactivo(boolean bitactivo) {
        this.bitactivo = bitactivo;
    }

    
    @Column(name="bitprimario", nullable=false)
    public boolean isBitprimario() {
        return this.bitprimario;
    }
    
    public void setBitprimario(boolean bitprimario) {
        this.bitprimario = bitprimario;
    }

    
    @Column(name="iddominio", nullable=false)
    public long getIddominio() {
        return this.iddominio;
    }
    
    public void setIddominio(long iddominio) {
        this.iddominio = iddominio;
    }

    
    @Column(name="idpersona", nullable=false)
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }

    
    @Column(name="strtelefono", nullable=false, length=30)
    public String getStrtelefono() {
        return this.strtelefono;
    }
    
    public void setStrtelefono(String strtelefono) {
        this.strtelefono = strtelefono;
    }




}


